// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// uart_tx //
// ------- //

#define uart_tx_wrap_target 0
#define uart_tx_wrap 5

static const uint16_t uart_tx_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0x86a0, //  1: pull   block                  [6] 
    0xe000, //  2: set    pins, 0                    
    0xe627, //  3: set    x, 7                   [6] 
    0x6001, //  4: out    pins, 1                    
    0x0644, //  5: jmp    x--, 4                 [6] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_tx_program = {
    .instructions = uart_tx_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config uart_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_tx_wrap_target, offset + uart_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

